port = 2873
address = 172.25.71.123
use chroot = false
read only = true
list = true
log file = /tmp/rsyncd-transfer.log
pid file = /tmp/rsyncd-transfer.pid
hosts allow = 172.20.103.218, 172.25.71.123, 127.0.0.1

[iraod_new]
    path = /home/storageSDA1/liaojr/IRAOD-New
    comment = IRAOD-New codebase

[sarclip_code]
    path = /home/storageSDA1/liaojr/SARCLIP
    comment = SARCLIP codebase

[rsar_dataset]
    path = /home/storageSDA1/liaojr/dataset/RSAR
    comment = RSAR dataset

[sarclip_dataset]
    path = /home/storageSDA1/Dataset/SARCLIP
    comment = SARCLIP weights and dataset assets
